version: '3.8'

services:
  app:
    build: .
    image: springboot-docker-demo
    container_name: springboot-demo-container
    ports:
      - "8081:8080"
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
